targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:
        options:
          # maybe_map: false
          # maybe_when: false